with open('core.subtle', encoding='utf8') as src:
    lines = src.read().splitlines()

with open('core.subtle.inc', encoding='utf8', mode='w') as f:
    f.write('// auto generated by gen.py, do not modify!\n')
    f.write('#ifndef SUBTLE_CORE_INC_H\n')
    f.write('#define SUBTLE_CORE_INC_H\n')
    f.write('const char* CORE_SOURCE =\n')
    for line in lines:
        f.write('"' + line.replace('"', '\"') + '\\n"\n')
    f.write(';\n')
    f.write('#endif\n')
